### ISSUE TITLE
Transparent window

### ISSUE THREAD

**Issue by Strykar** [NickvisionApps/Cavalier#141] opened 2024-01-10 19:07 UTC
Could the window be made transparent? Show the desktop background image instead.
And have no window decorations?

Currently its - https://i.imgur.com/xSqDNxk.png

**Comment by nlogozzo** [comment] 2024-01-11 20:04
I do not know if this is possible with GTK, but I will look into it :)

**Comment by Strykar** [comment] 2024-01-11 20:14
Aw, back to Kitty it is.
Thank you!

**Comment by nlogozzo** [comment] 2024-01-11 20:40
> I do not know if this is possible with GTK

https://docs.gtk.org/gtk4/method.Widget.set_opacity.html

Looks like we can! Will play around with it...

**Comment by THEGOLDENPRO** [comment] 2024-01-21 17:49
setting the background colour to complete transparency works for me on KDE

![image](https://github.com/NickvisionApps/Cavalier/assets/66202304/8a67fa3a-064f-4828-86ad-ff9d40c15bf2)

**Comment by fsobolev** [comment] 2024-02-06 03:19
hi @Strykar , sorry for late reply, I wasn't watching the repo for a while.
The window of Cavalier is actually fully transparent (https://github.com/NickvisionApps/Cavalier/blob/main/NickvisionCavalier.GNOME/Resources/org.nickvision.cavalier.css#L2), it's just the default background color drawn by Cavalier is identical to the one from Adwaita theme, giving impression that the window itself is not transparent. But the background color can be changed in settings to any other, including fully transparent, and together with "borderless window" setting it's possible to make Cavalier only show foreground bars like on screenshot above.
But on your screenshot I see the problem. Lack of rounded corners and very thick window borders indicate that there's no compositing available for the app (= no transparency). It means that either there's something wrong with your Cavalier installation, or there's something wrong with your graphics drivers, or you use Xorg window manager that has compositing disabled or doesn't provide it at all. In Xfce and KDE it's possible to enable/disable compositing in settings. If you use window manager that doesn't provide compositing (for example, openbox), take a look at [picom](https://wiki.archlinux.org/title/picom) or  [Xcompmgr](https://wiki.archlinux.org/title/Xcompmgr).

Anyway, there's nothing to do on Cavalier side, so I'm closing the issue.

**Closed by fsobolev** 2024-02-06 03:19 UTC
Labels: feature

**Comment by Strykar** [comment] 2024-02-06 03:26
Thanks for the update, I am using Gnome on Wayland with Nvidia's binary drivers.
I assumed everything under the hood was was working as Kitty terminal can do transparency fine.

**Comment by fsobolev** [comment] 2024-02-06 03:44
> using Gnome on Wayland with Nvidia's binary drivers.

I once has the same issue in GNOME (not with Nvidia tho, Intel graphics) with some flatpak apps, caused by specific versions mismatch of Mesa libraries on the host and inside flatpak (as I understood, at least). But updating everything and reboot solved it, so that's not your case I guess.
The only thing I can suggest is to run the app in a terminal (`flatpak run org.nickvision.cavalier` for flatpak or `snap run cavalier` for snap) and look if there are some error messages related to graphics that will maybe help you search for hints or possible solution.
Hope you will find a fix :)
